# Generated by Django 6.0 on 2026-01-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('absent', 'Absent'), ('present', 'Present'), ('late', 'Late'), ('secial_case', 'Special Case')], max_length=20),
        ),
    ]
