# Generated by Django 5.2 on 2026-01-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendanded_at',
            new_name='attended_at',
        ),
    ]
