# Generated by Django 6.0 on 2026-01-07 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_attendanded_at_attendance_attended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'session'), name='unqiue_user_per_session'),
        ),
    ]
