# Generated by Django 6.0 on 2026-01-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionVerify',
        ),
    ]
