# Generated by Django 5.2 on 2026-01-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twofa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
